language: node_js
node_js:
  "node"

cache: npm

env:
  global:
    - NODE_ENV=test

before_script:
  - npm install

after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
